version: '2.4'

services:

  sample-postgres:
    container_name: sample-postgres
    build: ./docker/postgres
    image: sample-postgres
    ports:
    - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
    - ./docker-data/postgres/data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/
    restart: always

  sample-nodejs:
    container_name: sample-nodejs
    build: ./docker/nodejs
    image: sample-nodejs
    volumes:
      - .:/app
    ports:
      - 8090:${PORT}
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - sample-postgres
    command: yarn prod
    restart: always

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - 9000:9000
    volumes:
      - ./docker-data/minio/data:/data
    command: server /data
    env_file:
      - .env
    restart: always

